name: product_list
description: A flutter application which will help in seeing the list of categories and products inside them.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  carousel_slider: ^3.0.0

  cupertino_icons: ^1.0.2

  data_connection_checker: ^0.3.4

  flutter:
    sdk: flutter

  flutter_blurhash: ^0.5.0

  flutter_secure_storage: ^4.1.0

  get: ^3.26.0

  google_fonts: ^2.0.0

  hive: ^2.0.0

  intl: ^0.17.0

  logger: ^0.9.4

  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true